# Generated by Django 3.1.5 on 2021-01-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('epnum', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('join_date', models.IntegerField()),
            ],
        ),
    ]
