# Generated by Django 3.1.5 on 2021-01-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(),
        ),
    ]
